#+OPTIONS: H:3 
#+OPTIONS: tex:dvipng
#+OPTIONS: toc:nil 
#+STARTUP: align oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n) export(e)
#+Date:  
#+TITLE: Draft for MA in Data Vis
#+AUTHOR: GC Digital Fellows (Draft)
#+LANGUAGE:   en
#+EXCLUDE_TAGS: noexport


#+LATEX_HEADER: \usepackage{attrib}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \let\iint\undefined 
#+LATEX_HEADER: \let\iiint\undefined 
#+LATEX_HEADER: \usepackage{dsfont}
#+LATEX_HEADER: \usepackage[autostyle]{csquotes}
#+LATEX_HEADER: \usepackage[backend=biber,style=authoryear-icomp,sortlocale=de_DE,natbib=true,url=false, doi=true,eprint=false]{biblatex}
#+LATEX_HEADER: \addbibresource{mybib.bib}
#+LATEX_HEADER: \addbibresource{/Users/emisshula/research/citations/refs.bib} 
#+LATEX_HEADER: \usepackage[retainorgcmds]{IEEEtrantools}
#+LATEX_HEADER: \author{Misshula, Evan\\ \texttt{Criminal Justice, CUNY Graduate Center}}
#+LATEX_HEADER: \title{Demonstration Of Instrumental Variables And Control Function Methods}
# \bibliography{mybib.bib,/Users/emisshula/research/citations/refs.bib} 

* Public Scholarship
- CUNY is a public university whose research is supported by and supports all levels
  of government. To the greatest extent possible, CUNY data visualization program
  should make its work available for public consumption and criticism.
- CUNY data visualization program should make use of its CUNY's ties to City 
  government and NY cultural institutions such as the NY Public library that 
  have their own efforts to broaden distribution of their data.
- CUNY data visualization program should be dedicated to increasing the public's
  data literacy.
- CUNY data visualization should dedicate itself to producing
  visualizations with the highest fidelity to the underlying data.
* Free Software
- Just as CUNY is an open public university, it should be mindful of the tools 
  that it trains students to use.
- The choice of computational tools has both political and
  philosophical implications.  Where practical, CUNY should show a
  strong preference for software that supports its own values. FREE
  software, where code is available for review, revision and customization
  should be the default.
- Just as the CUNY data visualization program's work should contribute information
  and understanding back to the levels of government that support CUNY.  CUNY should
  also seek to contribute to the community of FREE software through the default
  release of code, visualizations and conferences.
* Diversity
- One of CUNY's great strengths is its racial and economic diversity, the data visualization
  program should help to create data visualizations that build on this strength and weaken 
  rather than reinforce stereotypes.
- The program should also seek to recruit the broadest student body
  and provide as much technical training as possible.  The program
  should be an on-ramp for New York City residents and not just a place
  for the already digitally savvy.
* Web tools
- The program should aim to teach students the tools that allow for
  broadest distribution of their work.
- To the above stated goal, students should be able to create
  interactive visualizations inside the browser.
- Web Hosting resources are a critical piece of both the information
  technology and intellectual resources of the program.
* Causality over description
- When possible data visualizations should elucidate causal relationships
  rather than simply describing data.
* Documentation
- The highest principle of data visualization is fidelity to the data.
  Where this is not possible in one graph or scene in an interactive
  visualization any known distortions should be clearly disclosed.
- Sources of data should be adequately described.
- Whenever possible data should be made available in machine readable
  format for reproduciblity.

